name: Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with: { node-version: 16.x }

      - name: print github.ref
        run: |
          echo '${{ github.ref }}'
          node -p '`${{ github.ref }}`.split(`/`).at(-1)'
